HISTFILE="$XDG_CACHE_HOME/zsh/history"
[[ -d ${HISTFILE:h} ]] || mkdir -p ${HISTFILE:h}
HISTSIZE=100000
SAVEHIST=$HISTSIZE

setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
unsetopt HIST_REDUCE_BLANKS
unsetopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
